server:
  port: 9999


spring:
  application:
    name: springcloud-gateway


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}